### ISSUE TITLE
如何写正则表达式才能使用中文名字

### ISSUE THREAD

**Issue by a934990825** [ishiyamasayuri/FastLogin#1]
^[\u4e00-\u9fa5_a-zA-Z0-9]+$
[\u4e00-\u9fa5_a-zA-Z0-9]
^[\\u4e00-\\u9fa5_a-zA-Z0-9]+$
[\\u4e00-\\u9fa5_a-zA-Z0-9]
这些都不行

**Comment by KspTooi** [comment]
将配置文件中的Enable_UserNameStrictmode设置为false
